---
abstract: 'Base theme for Skryf'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires:
  Mojolicious: '0'
  Test::Mojo: '0'
  Test::More: '0'
  Test::NoTabs: '0'
  strict: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Skryf-Theme-Booshka
requires:
  File::Basename: '0'
  File::ShareDir: '0'
  File::Spec::Functions: '0'
  Mojo::Base: '0'
version: '1.04'
